apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: echo-server
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: echo-server
    repoURL: https://ealenn.github.io/charts
    targetRevision: '*'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
